# Generated by Django 3.1.2 on 2021-08-01 03:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aapl',
            name='StockDate',
            field=models.DateField(blank=True, default=datetime.date(2021, 7, 31)),
        ),
        migrations.AddField(
            model_name='dal',
            name='StockDate',
            field=models.DateField(blank=True, default=datetime.date(2021, 7, 31)),
        ),
        migrations.AddField(
            model_name='tsla',
            name='StockDate',
            field=models.DateField(blank=True, default=datetime.date(2021, 7, 31)),
        ),
    ]
