# Generated by Django 3.1.2 on 2021-08-02 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210731_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockDate', models.DateField(blank=True, default=datetime.date(2021, 8, 2))),
                ('Negative', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Neutral', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Positive', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Compound', models.DecimalField(decimal_places=2, max_digits=4)),
                ('StockOpen', models.DecimalField(decimal_places=2, max_digits=10)),
                ('StockHigh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('StockLow', models.DecimalField(decimal_places=2, max_digits=10)),
                ('StockClose', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CompanyName', models.CharField(max_length=50)),
                ('Ticker', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='AAPL',
        ),
        migrations.DeleteModel(
            name='DAL',
        ),
        migrations.DeleteModel(
            name='TSLA',
        ),
    ]
